apiVersion: v1
kind: Service
metadata:
  name: chuzone-frontend
  namespace: examen-26
  labels:
    app: chuzone-frontend
spec:
  type: NodePort
  selector:
    app: chuzone-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  sessionAffinity: None
